Drop old %triggerin scripts to unbreak the build
Rebuilding nfs-utils led to rpmbuild erroring out with:

error: line 262: Trigger fired by the same package is already defined in spec file: %triggerin -- nfs-utils < 1:1.3.1-4.0

To fix the build, this commit drops the old %triggerin scripts that
rpmbuild doesn't like. We are already at F24; the scripts were there to
support upgrades from nfs-utils 1.3.0 that was in F20 and upgrades from
F20 were only supported up to F22 on the distro level.